version: '3'

services:

  web:
    image: magento/magento-cloud-docker-nginx:latest
    links:
      - fpm
    volumes: &appvolumes
      - "./src:/app"
      - "./config/${ENV}/magento/.user.ini:/app/pub/.user.ini"
      - "./config/${ENV}/magento/env.php:/app/app/etc/env.php"
      - "./config/${ENV}/magento/config.php:/app/app/etc/config.php"
      - "./config/${ENV}/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "~/.composer/cache:/root/.composer/cache:delegated"
      - "~/.composer/auth.json:/root/.composer/auth.json:delegated"
      - "./composer/bin/composer:/usr/local/bin/composer:delegated"
    environment:
      VERBOSE: "true"
    networks:
      - "network-back"
      - "traefik_default"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.${DOCKER_PREFIX:-web}.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.services.${DOCKER_PREFIX:-web}.loadbalancer.server.port=80"

  cli:
    image: magento/magento-cloud-docker-php:7.2-cli-1.1
    volumes:  *appvolumes
    command: bash -c "php bin/magento setup:store-config:set --base-url='http://${HOSTNAME}/'; php bin/magento setup:store-config:set --base-url-secure='https://${HOSTNAME}/'; php bin/magento cron:install; rm -rf /app/generated/*; tail -f /dev/null"
    links:
      - mysql
    networks:
      - "network-back"

  fpm:
    image: magento/magento-cloud-docker-php:7.2-fpm-1.1
    links:
      - mysql
    volumes: *appvolumes
    environment:
      - "VERBOSE=true"
      - "UPDATE_UID_GID=true"
      - "MAGENTO_RUN_MODE=developer"
    networks:
      - "network-back"

  mysql:
    image: mysql:5.7
    hostname: "${DOCKER_PREFIX}.mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "magento"
      MYSQL_USER: "magento"
      MYSQL_PASSWORD: "magento"
    volumes:
      - "./var/mysql/dbdata:/var/lib/mysql"
    networks:
      - "network-back"
      - "traefik_default"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.tcp.routers.${DOCKER_PREFIX}.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.${DOCKER_PREFIX}.entrypoints=mysql"

networks:
  traefik_default:
    external: true
  network-back:
    external: true
