version: '3'

services:

  web:
    image: magento/magento-cloud-docker-nginx:latest
    links:
      - fpm
    volumes: &appvolumes
      - "./src:/app:delegated"
      - "./config/dev/cron/crontabs/root:/etc/cron.d/root"
      #- "./config/${ENV}/magento/.user.ini:/app/pub/.user.ini"
      #- "./config/${ENV}/magento/env.php:/app/app/etc/env.php"
      #- "./config/${ENV}/magento/config.php:/app/app/etc/config.php"
      #- "./config/${ENV}/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "~/.composer/cache:/root/.composer/cache:delegated"
      - "./composer/auth.json:/root/.composer/auth.json:delegated"
      #- "./composer/bin/composer:/usr/local/bin/composer:delegated"
    environment:
      VERBOSE: "true"
    networks:
      - "network-back"
      - "traefik_default"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.${DOCKER_PREFIX:-web}.rule=Host(`${HOSTNAME:- }`)"
      - "traefik.http.routers.${DOCKER_PREFIX:-web}.tls=true"
      - "traefik.http.routers.${DOCKER_PREFIX:-web}.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.${DOCKER_PREFIX:-web}.entrypoints=websecure"
      - "traefik.http.routers.${DOCKER_PREFIX:-web}.middlewares=${DOCKER_PREFIX:-web}@docker"
      - "traefik.http.services.${DOCKER_PREFIX:-web}.loadbalancer.server.port=80"
      - "traefik.http.middlewares.${DOCKER_PREFIX:-web}.compress=true"

  cli:
    image: magento/magento-cloud-docker-php:7.2-cli-1.1
    volumes:  *appvolumes
    command: bash -c "${NEW_DATABASE_COMMAND:- }${COMPOSER_INSTALL_COMMAND:- }${MAGENTO_INSTALL_COMMAND:- } php bin/magento setup:store-config:set --base-url='https://${HOSTNAME:- }/'; php bin/magento setup:store-config:set --base-url-secure='https://${HOSTNAME:- }/'; php bin/magento c:fl; service cron start; crontab /etc/cron.d/root; rm -rf /app/generated/*; service sendmail stop; tail -f /dev/null"
    environment: &appenvironment
      - "VERBOSE=true"
      - "UPDATE_UID_GID=true"
      - "MAGENTO_RUN_MODE=developer"
    networks:
      - "network-back"

  fpm:
    image: magento/magento-cloud-docker-php:7.2-fpm-1.1
    volumes: *appvolumes
    environment: *appenvironment
    networks:
      - "network-back"

networks:
  traefik_default:
    external: true
  network-back:
    external: true
