version: "3.3"

services:

  traiefik:
    image: "traefik:latest"
    restart: unless-stopped
    command: --api
    command: --docker
    command:
      - "--log.level=INFO"
      - "--configFile=/traefik.toml"
      - "--api"  
      - "--api.insecure=true"
      - "--providers.docker=true" 
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.mysql.address=:3306"  
    networks:
      - "traefik_default"
    ports:
      - "443:443"
      - "80:80"
      - "3306:3306"
      - "8080:8080"  
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:traefik.localhost-carrefour.com"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_default:"

networks:
  traefik_default:
    external: true
