# uncomment this line to get debug info with "docker logs":
debug = true
logLevel = "INFO"
defaultEntryPoints = ["https","http"]
# The syntax is somewhat esoteric so this is mostly copy-paste
[entryPoints]

    [entryPoints.web]
    address = ":80"
        [entryPoints.web.http.redirections.entryPoint]
         to = "websecure"
         scheme = "https"
        #[entryPoints.http.redirect]
        #entryPoint = "https"

    [entryPoints.websecure]
    address = ":443"
        [entryPoints.websecure.tls]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "localhost-carrefour.com"
watch = true
exposedbydefault = false

[acme]
email = "glenn@astralwebinc.com"
storage = "/acme.json"
# problems with let's encrypt? You can use this staging environment,
# if you have to do a lot of trial and error:
#caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
entryPoint = "https"
OnHostRule = true

[acme.httpChallenge]
entryPoint = "http"
# enable web configuration backend.
[web]
# Web administration port, proxied in docker-compose.yml
address = ":80"

#2020 GitHub, Inc.
